# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'mhd-http2'
tagline:          'libmicrohttpd-http2'
description:      'An HTTP/2 implementation for GNU libmicrohttpd'
url:              'https://maru.github.io'
baseurl:          '/libmicrohttpd-http2/'
repository:       'maru/libmicrohttpd-http2'
version:          0.1.0

author:
  name:           'Maru Berezin'
  url:            https://twitter.com/maruberezin


logo: /assets/img/logo.jpg

# breadcrumbs: false
# search: true
# search_full_content: true
include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: false
      sidebar:
        nav: "navbar"
